### PR TITLE
Fix #16: JSON get does not handle missing cookie

### LINKED ISSUE #16: JSON get does not handle missing cookie
public synchronized String get(String name) returns null when cookie is not present. The JSON variant does not checks returned value and passes null to object mapper where NPE is thrown.

public <T> T get(String name, Class<T> dataType) throws CookieParseException {
        String value = this.get(name);
        try {
            return this.mapper.readValue(value, dataType);
        } catch (IOException var5) {
            throw new CookieParseException(var5);
        }
    }

### PR DESCRIPTION
**Pull request by tholu**
Resolves #16.

### CODE REVIEW

File: src/main/java/com/github/jscookie/javacookie/Cookies.java [hunk 1]
```diff
@@ -75,6 +78,9 @@ public synchronized String get( String name ) {
 	@Override
 	public <T> T get( String name, TypeReference<T> typeRef ) throws CookieParseException {
 		String value = get( name );
+		if(value == null) {
```
Comment (FagnerMartinsBrack) [inline src/main/java/com/github/jscookie/javacookie/Cookies.java]: This should be `if ( value == null )` to be consistent with the rest of the file
```suggestion
		if ( value == null ) {
```

It might be worth only release a breaking v1 once we fix this NullPointer hell. Perhaps introducing a [NullObjectPattern](https://en.wikipedia.org/wiki/Null_object_pattern)?

File: src/main/java/com/github/jscookie/javacookie/Cookies.java [hunk 2]
```diff
@@ -65,6 +65,9 @@ public synchronized String get( String name ) {
 	@Override
 	public <T> T get( String name, Class<T> dataType ) throws CookieParseException {
 		String value = get( name );
+		if(value == null) {
```
Comment (FagnerMartinsBrack) [inline src/main/java/com/github/jscookie/javacookie/Cookies.java]: This should be `if ( value == null )` to be consistent with the rest of the file
```suggestion
		if ( value == null ) {
```

It might be worth only release a breaking v1 once we fix this NullPointer hell. Perhaps introducing a [NullObjectPattern](https://en.wikipedia.org/wiki/Null_object_pattern)?

File: src/main/java/com/github/jscookie/javacookie/Cookies.java (hunk 1 above)
Comment (tholu) [reply src/main/java/com/github/jscookie/javacookie/Cookies.java]: Sorry, me IDEA has another idea of Java code formatting, I'll fix it. I would go with `Optional`s to fix the NullPointer hell.

**Comment by FagnerMartinsBrack** [comment]
Cool, great stuff!
